play_latest:
  description: Play the latest episode
  fields:
    program_name:
      description: The name of the DRTV program.
      example: "rapport"
    entity_id:
      description: Name(s) of entities to play on.
      example: "media_player.living_room_chromecast"
play_channel:
  description: Play the a specified channel
  fields:
    channel:
      description: The name of the channel.
      example: "dr1"
    entity_id:
      description: Name(s) of entities to play on.
      example: "media_player.living_room_chromecast"
    subtitles:
      description: Show subtitles
      example: "true"
